"""
Seed English olympiad tests into the database.

Idempotent: a test is identified by (grade, subject, title). If a test with
the same key already has questions, it is left untouched. Re-running after
adding new grades only inserts the new ones.

Run locally (reads backend/.env -> Supabase):
    python manage.py seed_tests
"""
from django.core.management.base import BaseCommand
from apps.tests_app.models import Subject, Test, Question

SUBJECT_NAME = "Ingliz tili"
DURATION_MINUTES = 20
PASSING_PERCENTAGE = 70.0

# Each question: (question_text, option_a, option_b, option_c, correct_answer)
TESTS = [
    {
        "grade": 2,
        "title": "2-sinf Ingliz tili",
        "questions": [
            ('Complete the sentence: "I ...... a big dog, but my sister ...... a small cat."', "have got / has got", "has got / have got", "am / is", "A"),
            ('Which sentence is grammatically CORRECT?', "He like milk.", "He likes milk.", "He liking milk.", "B"),
            ('Choose the correct plural form of the word "BOX":', "Boxs", "Boxes", "Boxies", "B"),
            ('It is an animal. It has got a long trunk and big ears. What is it?', "A monkey", "An elephant", "A tiger", "B"),
            ('Choose the correct pronoun: "This is my mother. ...... is a teacher."', "He", "She", "It", "B"),
            ('Find the opposite of the word "TALL":', "Short", "Long", "Big", "A"),
            ('Days of the week: "Monday, Tuesday, ......, Thursday". What is missing?', "Friday", "Wednesday", "Sunday", "B"),
            ('Complete the sentence: "The book is ...... the table." (ustida)', "in", "under", "on", "C"),
            ('Choose the correct question word: "— ...... is your name? — My name is Ali."', "Who", "What", "Where", "B"),
            ('Which word means "oshxona" in English?', "Living room", "Bedroom", "Kitchen", "C"),
            ('Complete the sentence: "We ...... football every Sunday."', "play", "plays", "playing", "A"),
            ('Find the ODD word in this food group:', "Bread", "Milk", "Pencil", "C"),
            ('Choose the correct answer: "Can a fish swim?"', "Yes, it can.", "No, it can't.", "Yes, I can.", "A"),
            ('What is the correct spelling for the number 15?', "Fiveteen", "Fifteen", "Fifty", "B"),
            ('Complete the sentence: "These are my ......" (plural)', "toy", "toys", "toyes", "B"),
            ('Choose the correct question word: "— ...... old are you? — I am eight."', "How", "What", "Why", "A"),
            ('Complete the sentence: "An orange is orange, but a banana is ......"', "red", "green", "yellow", "C"),
            ('Look at the sentence: "He doesn\'t ...... apples."', "likes", "like", "liking", "B"),
            ('Which room is used for sleeping?', "Bathroom", "Bedroom", "Kitchen", "B"),
            ('Choose the correct article: "I can see ...... umbrella."', "a", "an", "two", "B"),
        ],
    },
    {
        "grade": 3,
        "title": "3-sinf Ingliz tili",
        "questions": [
            ('Complete the sentence: "Look! The children ...... in the garden right now."', "is playing", "are playing", "play", "B"),
            ('Choose the correct plural form of the word "FOOT":', "Foots", "Feet", "Feets", "B"),
            ('Complete the comparison: "A horse is big, but an elephant is ......"', "bigger", "biggest", "small", "A"),
            ('Choose the correct sentence:', "She don't like bananas.", "She doesn't likes bananas.", "She doesn't like bananas.", "C"),
            ('Look at the clock: It is 08:30. How do we say this?', "It's half past eight.", "It's eight o'clock.", "It's a quarter to eight.", "A"),
            ('Complete the sentence: "There ...... some milk in the fridge."', "is", "are", "am", "A"),
            ('Find the CORRECT spelling for the month:', "Febuary", "February", "Februery", "B"),
            ('Choose the correct preposition: "The mouse is hiding ...... the armchair." (orqasida)', "in front of", "behind", "between", "B"),
            ('What is the opposite of the word "BEAUTIFUL"?', "Ugly", "Pretty", "Nice", "A"),
            ('Complete the question: "— ...... do you live? — I live in Tashkent."', "What", "Who", "Where", "C"),
            ('Choose the correct word: "This is my brother. ...... name is Akmal."', "His", "Her", "Its", "A"),
            ('Complete the sentence: "I always get up ...... 7 o\'clock in the morning."', "on", "at", "in", "B"),
            ('Which animal is the FASTEST?', "A cheetah", "A turtle", "A cat", "A"),
            ('Complete the sentence: "They ...... to school yesterday." (past)', "go", "went", "going", "B"),
            ('Choose the correct plural form of the word "MOUSE":', "Mouses", "Mices", "Mice", "C"),
            ('Complete the sentence: "Excuse me, ...... I borrow your pencil, please?"', "must", "can", "am", "B"),
            ('Find the ODD word in this weather group:', "Rainy", "Sunny", "Kitchen", "C"),
            ('Complete the sentence: "My mother\'s sister is my ......"', "aunt", "uncle", "grandmother", "A"),
            ('Choose the correct sentence:', "I am taller than my friend.", "I am more tall than my friend.", "I am tallest than my friend.", "A"),
            ('Complete the question: "— ...... pencils have you got? — I have got five."', "How much", "How many", "Who", "B"),
        ],
    },
    {
        "grade": 4,
        "title": "4-sinf Ingliz tili",
        "questions": [
            ('Complete the sentence: "We ...... a great movie at the cinema last night."', "see", "saw", "seen", "B"),
            ('Choose the correct sentence with the superlative adjective:', "Russia is the biggest country in the world.", "Russia is the most big country in the world.", "Russia is bigger than country in the world.", "A"),
            ('Complete the sentence: "This is Akmal\'s book. Please give it to ......"', "he", "him", "his", "B"),
            ('Choose the correct modal verb: "The traffic light is red. You ...... stop!"', "must", "shouldn't", "can", "A"),
            ('Complete the question: "— ...... did you go on holiday? — We went to Samarkand."', "When", "Where", "Why", "B"),
            ('Look at the sentence: "They ...... any homework yesterday."', "didn't had", "didn't have", "don't have", "B"),
            ('Find the CORRECT plural form of the word "KNIFE":', "Knifes", "Knives", "Knivs", "B"),
            ('Choose the correct preposition of time: "My birthday is ...... June 15th."', "in", "on", "at", "B"),
            ('What is the opposite of the word "HEAVY"?', "Light", "Thin", "Weak", "A"),
            ('Complete the sentence: "I am interested ...... reading English books."', "at", "on", "in", "C"),
            ('Which word is a profession?', "Engineer", "Clever", "Office", "A"),
            ('Complete the sentence: "Anvar is ...... student in our class. He always gets A+."', "the better", "the best", "goodest", "B"),
            ('Choose the correct sentence:', "How much cost this pen?", "How much does this pen cost?", "How many does this pen cost?", "B"),
            ('Complete: "Yesterday, Sarah ...... up early, ...... her breakfast, and went to school."', "woke / ate", "wakes / eats", "woked / eated", "A"),
            ('Choose the correct word: "There are ...... apples, but there isn\'t ...... juice."', "any / some", "some / any", "much / many", "B"),
            ('Complete the sentence: "You have an exam tomorrow. You ...... study tonight."', "should", "shouldn't", "must to", "A"),
            ('Find the word that does NOT belong to the "Health" group:', "Headache", "Toothache", "Homework", "C"),
            ('Complete the sentence: "This car belongs to my parents. It is ......"', "theirs", "our", "mine", "A"),
            ('Choose the correct spelling for the ordinal number 12:', "Twelth", "Twelfth", "Twelve", "B"),
            ('"October is the tenth month. What is the twelfth month?"', "November", "January", "December", "C"),
        ],
    },
    {
        "grade": 5,
        "title": "5-sinf Ingliz tili",
        "questions": [
            ('Complete: "I think it ...... rain tomorrow, so you should take an umbrella."', "will", "is going to", "was", "A"),
            ('Choose the correct sentence with a long adjective:', "This book is more interestinger than that one.", "This book is more interesting than that one.", "This book is most interesting than that one.", "B"),
            ('Complete: "Don\'t touch that bicycle! It isn\'t yours, it is ......"', "her", "hers", "she", "B"),
            ('Choose the correct words: "How ...... money do you need? There are ...... books to buy."', "many / much", "much / many", "much / much", "B"),
            ('Complete: "We ...... to Paris last summer, and we ...... a great time."', "go / have", "went / had", "gone / had", "B"),
            ('Choose the correct question word: "— ...... does this bus leave? — At 9 o\'clock."', "What time", "How long", "Where", "A"),
            ('Find the CORRECT plural form of the word "CITY":', "Citys", "Cities", "Cityes", "B"),
            ('Complete: "Look at those dark clouds! It ...... rain very soon."', "will", "is going to", "rains", "B"),
            ('What is the opposite of the word "CHEAP"?', "Expensive", "Difficult", "Modern", "A"),
            ('Complete with prepositions: "We go to the beach ...... summer ...... July."', "on / in", "in / in", "at / on", "B"),
            ('Which word is NOT a natural disaster?', "Earthquake", "Flood", "Greenhouse", "C"),
            ('Complete: "This is ...... restaurant in the city. The food here is terrible!"', "the worst", "the baddest", "the worse", "A"),
            ('Choose the correct sentence:', "She speaks English very good.", "She speaks English very well.", "She speaks English very goodly.", "B"),
            ('Complete the dialogue: "Would you like some cake?" — "Yes, ......, please."', "I would", "just a little", "just a few", "B"),
            ('Choose the correct sentence structure:', "He always is late for school.", "He is always late for school.", "Always he is late for school.", "B"),
            ('Complete: "If you are tired, you ...... go to bed early."', "shouldn't", "ought to", "don't have to", "B"),
            ('Find the noun that is UNCOUNTABLE:', "Water", "Bottle", "Glass", "A"),
            ('Complete: "I don\'t know the answer. Can you help ......, please?"', "I", "my", "me", "C"),
            ('Choose the correct spelling for the number 40:', "Fourty", "Forty", "Fortty", "B"),
            ('Complete the logical chain: "Spring, Summer, Autumn, ......"', "Winter", "Weather", "Season", "A"),
        ],
    },
    {
        "grade": 6,
        "title": "6-sinf Ingliz tili",
        "questions": [
            ('Identify the grammatically CORRECT sentence with a stative verb:', "I am knowing the answer to this puzzle.", "I know the answer to this puzzle.", "I have been knowing the answer.", "B"),
            ('Complete: "Hardly ...... entered the classroom when the exam bell rang."', "had the teacher", "the teacher had", "did the teacher", "A"),
            ('Choose the correct collective noun: "A ...... of wolves chased the deer."', "flock", "herd", "pack", "C"),
            ('Mixed conditional: "If she ...... harder last year, she would be a student now."', "studied", "had studied", "would have studied", "B"),
            ('Complete the idiom: "It\'s just a storm in a ......."', "teacup", "glass", "ocean", "A"),
            ('Choose the correct phrase: "The match was postponed ...... the heavy rainstorm."', "because", "due to", "in spite of", "B"),
            ('Which pronoun is correct: "Everyone must bring ...... own dictionary."', "his or her", "their", "its", "A"),
            ('Complete: "I look forward to ...... you at the competition next month."', "meet", "meeting", "met", "B"),
            ('Choose the correct form: "This building is said ...... built in the 15th century."', "to be", "to have been", "being", "B"),
            ('What is the antonym of the word "GENEROUS"?', "Stingy", "Brave", "Honest", "A"),
            ('Complete: "The sharper the knife, ...... it cuts the meat."', "easily", "the more easily", "the most easily", "B"),
            ('Fill in the blank: "Neither the students nor the teacher ...... present yesterday."', "was", "were", "are", "A"),
            ('Choose the correct phrasal verb: "We have ...... sugar. Can you buy some?"', "run out of", "put up with", "look up to", "A"),
            ('Complete: "I wish I ...... so much homework to do tonight."', "don't have", "didn't have", "hadn't had", "B"),
            ('Choose the option for a temporary situation: "This week he ...... a seminar in Samarkand."', "attends", "is attending", "has attended", "B"),
            ('Identify the uncountable noun:', "Information", "Job", "Assignment", "A"),
            ('Complete: "He is ...... intelligent boy that he solved it in a minute."', "so", "such an", "very", "B"),
            ('Choose the correct relative clause: "The book ...... cover is blue belongs to the librarian."', "which", "whose", "that", "B"),
            ('What does the idiom "piece of cake" mean?', "Something very delicious", "Something very easy", "A dangerous situation", "B"),
            ('"If a triangle has three equal sides, it is called an ...... triangle."', "isosceles", "equilateral", "right-angled", "B"),
        ],
    },
    {
        "grade": 7,
        "title": "7-sinf Ingliz tili",
        "questions": [
            ('Choose the CORRECT passive form: "They are painting the house now."', "The house is painted now.", "The house is being painted now.", "The house has been painted now.", "B"),
            ('Complete the reported speech: "I don\'t like horror movies," said Tom.', "Tom said that he doesn't like horror movies.", "Tom said that he didn't like horror movies.", "Tom said he likes horror movies.", "B"),
            ('"If I ...... you, I would take that job offer."', "am", "was", "were", "C"),
            ('Identify the sentence with correct GERUND usage:', "He refused answering the questions.", "He avoided answering the questions.", "He wanted answering the questions.", "B"),
            ('"By the time we arrived, the train ......"', "left", "has left", "had left", "C"),
            ('Complete the tag question: "You haven\'t finished your project yet, ......?"', "have you", "haven't you", "did you", "A"),
            ('Which sentence is grammatically INCORRECT?', "I am looking forward to seeing you.", "I suggest you to study harder.", "She let him go home early.", "B"),
            ('"Unless you ...... your passport, you won\'t be able to travel."', "will show", "show", "don't show", "B"),
            ('Complete the logical chain: "Success is a journey, not a ......"', "destination", "departure", "direction", "A"),
            ('"The cake was ...... delicious ...... I ate three pieces."', "so / that", "such / that", "too / to", "A"),
            ('Choose the correct modal for deduction: "She\'s not answering; she ...... be sleeping."', "can", "must", "should", "B"),
            ('Complete: "I\'d rather ...... at home tonight than go to the party."', "stay", "staying", "to stay", "A"),
            ('"The book ...... by a famous author is very popular."', "writing", "written", "wrote", "B"),
            ('Complete: "She is the woman ...... husband is a scientist."', "who", "whom", "whose", "C"),
            ('"It\'s high time you ...... to look for a job."', "start", "started", "have started", "B"),
            ('Which word is NOT a synonym for "ANGRY"?', "Furious", "Content", "Irritated", "B"),
            ('Complete: "They are said ...... all over the world."', "to travel", "to have traveled", "traveling", "A"),
            ('"I ...... my keys. Can you help me look for them?"', "have lost", "lost", "was losing", "A"),
            ('"The boy ...... in the corner is my cousin."', "sit", "sitting", "sat", "B"),
            ('Choose the sentence with the correct word order:', "Rarely he goes to the cinema.", "Rarely does he go to the cinema.", "He goes rarely to the cinema.", "B"),
        ],
    },
    {
        "grade": 8,
        "title": "8-sinf Ingliz tili",
        "questions": [
            ('Complete the causative sentence: "I didn\'t fix my computer myself; I ......"', "fixed it", "had it fixed", "have fixed it", "B"),
            ('Reported Speech for: "Where did you go yesterday?" asked he.', "He asked where I had gone the day before.", "He asked where I went yesterday.", "He asked where did I go the day before.", "A"),
            ('"If he ...... the exam, he would be studying at university now."', "passed", "had passed", "would pass", "B"),
            ('Which sentence uses the correct passive structure?', "The report is being written by the students all morning.", "The report has been being written since morning.", "The report is written by the students since morning.", "B"),
            ('"I\'d rather ...... him the truth yesterday."', "have told", "told", "tell", "A"),
            ('Complete: "It\'s no use ...... about the past; nothing can be changed."', "to cry", "cry", "crying", "C"),
            ('Choose the correct phrasal verb: "I ...... my grandfather; he is the most honest man."', "run out of", "look up to", "get along with", "B"),
            ('"By this time tomorrow, we ...... the project."', "will finish", "will have finished", "will be finishing", "B"),
            ('"The boy ...... in the accident was sent to hospital."', "injured", "injuring", "was injured", "A"),
            ('Complete: "I wish I ...... more time to read English novels."', "had", "have", "would have", "A"),
            ('Which word is a synonym for "ANCIENT"?', "Modern", "Antique", "Current", "B"),
            ('Complete: "He is ...... hardworking that he never leaves work before 9 PM."', "such an", "so", "too", "B"),
            ('"Hardly ...... into the room when the lights went out."', "did I walk", "had I walked", "I walked", "B"),
            ('Choose the sentence with the correct (inverted) word order:', "Never I have seen such a beautiful sunset.", "Never have I seen such a beautiful sunset.", "I have never saw such a beautiful sunset.", "B"),
            ('"I\'m not used to ...... up this early in the morning."', "wake", "waking", "waked", "B"),
            ('Complete the tag question: "Let\'s go for a walk, ......?"', "will we", "shall we", "let we", "B"),
            ('"The decision ...... by the committee will be announced tomorrow."', "made", "to make", "making", "A"),
            ('Choose the correct collocation: "We need to ...... a decision quickly."', "do", "make", "get", "B"),
            ('"He behaves ...... he were the boss here."', "as though", "as if", "Both A and B are correct", "C"),
            ('"If I ...... you, I ...... that car."', "were / wouldn't buy", "was / won't buy", "am / didn't buy", "A"),
        ],
    },
    {
        "grade": 9,
        "title": "9-sinf Ingliz tili",
        "questions": [
            ('Complete with the correct inversion: "No sooner ...... than the electricity went out."', "had I reached home", "did I reach home", "I had reached home", "A"),
            ('Cleft sentence: "It was ...... who spearheaded the entire IT project last year."', "he", "him", "his", "A"),
            ('"Had it not been for your timely intervention, the company ...... bankrupt last quarter."', "would go", "would have gone", "had gone", "B"),
            ('"The committee recommended that the budget ...... reallocated to research immediately."', "is", "be", "should being", "B"),
            ('Complete the participle clause: "...... the final exam ahead of schedule, Bob felt relief."', "Having been finished", "Having finished", "Finishing", "B"),
            ('"The professor\'s explanation was so ...... that even novice students understood the theorem."', "ambiguous", "lucid", "obscure", "B"),
            ('"I would rather you ...... disclosure agreements before discussing the project yesterday."', "hadn't signed", "didn't sign", "wouldn't sign", "A"),
            ('Complete the modifier: "...... by the sharp decline in profits, the CEO called a meeting."', "Perturbed", "Perturbing", "Having perturbed", "A"),
            ('Identify the correct non-finite clause:', "Walking down the street, the heavy rain soaked my clothes.", "Walking down the street, I was soaked by the heavy rain.", "Walking down the street, my clothes became wet.", "B"),
            ('What does "to play devil\'s advocate" mean?', "To support an evil cause deliberately.", "To argue against an idea to test its validity.", "To refuse to take part in a legal argument.", "B"),
            ('Choose the correct prepositional idiom: "His strict adherence ...... the policy is exemplary."', "to", "with", "on", "A"),
            ('"...... , but it was also incredibly tedious."', "Not only", "Not only long", "Not only was the lecture long", "C"),
            ('"The newly developed software is said ...... meticulously tested before its launch last week."', "to be", "to have been", "being", "B"),
            ('"The suspect denied ...... anywhere near the crime scene on the night of the burglary."', "to be", "having been", "to have been", "B"),
            ('"Lest the confidential data ...... leaked, the admin implemented MFA."', "should be", "will be", "is", "A"),
            ('Find the synonym for "EPHEMERAL":', "Everlasting", "Transient", "Permanent", "B"),
            ('"The archeologist discovered an artifact, ...... origin remains a mystery."', "which", "whose", "of which the", "B"),
            ('"She acted with utmost ......; nobody knew she was switching to a rival company."', "candor", "stealth", "magnanimity", "B"),
            ('"If you ...... to encounter any technical anomalies, notify the supervisor."', "should", "were", "would", "A"),
            ('"Because the evidence was entirely ......, the judge dismissed the case."', "irrefutable", "unsubstantiated", "meticulous", "B"),
        ],
    },
    {
        "grade": 10,
        "title": "10-sinf Ingliz tili",
        "questions": [
            ('"Seldom ...... such a complex set of bureaucratic procedures in my career."', "I have encountered", "have I encountered", "I encountered", "B"),
            ('Causative: "The firm ...... its outdated protocols ...... by the experts last month."', "had / updated", "has / updating", "had / updating", "A"),
            ('"It is high time you ...... the implications of your decisions on the timeline."', "consider", "considered", "should consider", "B"),
            ('Choose the most appropriate academic synonym for "REDUCE":', "Aggravate", "Mitigate", "Emulate", "B"),
            ('"...... the weather forecast, we proceeded with the outdoor logistics plan."', "Despite", "In spite of", "Although", "A"),
            ('"Were he to disclose the confidential information, he ...... face severe legal ramifications."', "will", "would", "could have", "B"),
            ('"The candidate\'s arguments were ...... persuasive ...... the board voted in his favor."', "so / that", "such / that", "too / to", "A"),
            ('Choose the correct modal perfect: "He ...... his keys at the office, as I remember him locking the door with them."', "must have left", "can't have left", "should have left", "A"),
            ('"Not until the final results were published ...... the true magnitude of the discovery."', "did the scientists realize", "the scientists realized", "have the scientists realized", "A"),
            ('What does "to burn the midnight oil" mean?', "To work until very late at night.", "To waste resources uselessly.", "To be extremely angry.", "A"),
            ('"Having ...... from the long journey, the delegates were not in the mood for a briefing."', "just returning", "just returned", "just been returning", "B"),
            ('"The building, ...... foundation was laid in 1905, is now a protected heritage site."', "which", "whose", "of which", "B"),
            ('"If it ...... been for the lack of funding, the expedition would have succeeded."', "hadn't", "had not", "weren't", "A"),
            ('Complete the formal phrase: "...... any issues arise, please contact the support center."', "If", "Should", "Were", "B"),
            ('"The new policy ...... by next Monday, provided the director approves it."', "will be implemented", "will have been implemented", "is being implemented", "B"),
            ('Choose the correct collocation: "The proposal received ...... support from the faculty."', "robust", "heavy", "strongish", "A"),
            ('"The architect designed the building ...... it would be energy-efficient."', "so as to", "so that", "in order to", "B"),
            ('"She ...... of plagiarism, although she strongly denied the allegations."', "is accused", "was accused", "has been accused", "B"),
            ('"Little ...... that their entire plan had been compromised."', "they knew", "did they know", "they have known", "B"),
            ('"An ...... agreement is one that is implied rather than explicitly stated."', "explicit", "tacit", "overt", "B"),
        ],
    },
    {
        "grade": 11,
        "title": "11-sinf Ingliz tili",
        "questions": [
            ('"On no account ...... to share your multi-factor authentication credentials with anyone."', "you are permitted", "are you permitted", "did you permit", "B"),
            ('Mixed conditional: "...... my final year thesis earlier, I would not be experiencing this pressure today."', "Had I completed", "If I completed", "Should I complete", "A"),
            ('"The dean insisted that the research paper ...... published without further peer review."', "not be", "isn't", "not being", "A"),
            ('Choose the most precise C2-level word for "unintentional / by accident":', "Inadvertent", "Meticulous", "Conspicuous", "A"),
            ('"...... had the physicist initiated the particle accelerator than a systemic anomaly was detected."', "Hardly", "Scarcely", "No sooner", "C"),
            ('"The candidate spoke with absolute ......; she didn\'t hide any facts about her employment."', "candor", "stealth", "ambiguity", "A"),
            ('"But for your unwavering support during the crisis, our tech startup ......"', "would fail", "would have failed", "had failed", "B"),
            ('"I would rather you ...... the confidential files during yesterday\'s board meeting."', "hadn't downloaded", "didn't download", "wouldn't download", "A"),
            ('"The ancient manuscript is estimated ...... written by an anonymous monk in the 12th century."', "to be", "to have been", "having been", "B"),
            ('What is the meaning of the idiom "to cut corners"?', "To do something the easiest/cheapest way, sacrificing quality.", "To design a building with precise geometric structures.", "To make a sharp logical conclusion.", "A"),
            ('"Under the bed ...... where the frightened kitten had hidden during the thunderstorm."', "did it lay", "lay the place", "was the spot", "C"),
            ('"The CEO\'s decision was deemed ...... by the shareholders; it was completely logical."', "irrefutable", "unsubstantiated", "obsolete", "A"),
            ('Choose the correct prepositional idiom: "Her profound expertise ...... quantum cryptography was invaluable."', "at", "in", "with", "B"),
            ('"Lest the system ...... compromised, the engineer initiated a complete database encryption."', "should be", "will be", "is", "A"),
            ('"I don\'t recall ...... that specific clause in the agreement when we signed it last week."', "to see", "having seen", "to have seen", "B"),
            ('Identify the sentence that avoids a "dangling modifier":', "Having finished the experiment, the report was compiled by the students.", "Having finished the experiment, the students compiled the report.", "Having finished the experiment, the computer printed the results.", "B"),
            ('"The project manager works with utmost ......; she never overlooks even the smallest detail."', "negligence", "meticulousness", "complacency", "B"),
            ('Choose the correct formal inversion: "...... you experience any structural anomalies, contact the developer."', "Should", "Were", "Had", "A"),
            ('"The artifacts, ...... origin dates back to the Mesopotamian era, are on display at the museum."', "which", "whose", "of which the", "B"),
            ('"The company\'s expansion plans were completely ...... upon receiving the regulatory approvals."', "contingent", "dynamic", "intrinsic", "A"),
        ],
    },
    {
        "grade": 1,
        "subject": "Rus tili",
        "title": "1-sinf Rus tili",
        "questions": [
            ("Какое сочетание букв всегда пишется с буквой И?", "ЖЫ / ШЫ", "ЖИ / ШИ", "ЖЕ / ШЕ", "B"),
            ("Найдите слово, в котором допущена ОШИБКА:", "Чудо", "Чяшка", "Жираф", "B"),
            ("Сколько гласных букв в русском языке? (Букв, а не звуков!)", "6", "10", "5", "B"),
            ('Разгадайте слово из букв: "К, О, Л, Ш, А".', "Школа", "Класс", "Карандаш", "A"),
            ("Какая буква НЕ обозначает звука?", "Й", "Ь (мягкий знак)", "У", "B"),
            ("Какое слово пишется с большой буквы в любом месте предложения?", "Москва", "Город", "Собака", "A"),
            ("Укажите сочетание, которое пишется с буквой А:", "Ч...до", "Ч...шка", "Щ...ка", "B"),
            ('Какое слово является антонимом к слову "ДЕНЬ"?', "Солнце", "Ночь", "Вечер", "B"),
            ("В каком слове букв БОЛЬШЕ, чем звуков?", "Юра", "Мальчик", "Слон", "B"),
            ("Какое сочетание букв пишется с буквой У?", "ЧУ / ЩУ", "ЧО / ЩО", "ЧА / ЩА", "A"),
            ('Разделите слово "СОБАКА" для переноса. Какой вариант правильный?', "Со-бака", "С-обака", "Собак-а", "A"),
            ("Какое животное лишнее в этом списке?", "Корова", "Лошадь", "Волк", "C"),
            ("С какого знака препинания начинается реплика в диалоге?", "Точка", "Тире ( — )", "Вопросительный знак", "B"),
            ("Укажите слово, в котором пропущена буква Т:", "Прекрас...ный", "Чес...ный", "Опас...ный", "B"),
            ('Какая буква стоит в алфавите после буквы "М"?', "Л", "Н", "О", "B"),
            ("Найдите слово, которое обозначает ОДИН предмет:", "Книги", "Карандаш", "Столы", "B"),
            ('Какое слово отвечает на вопрос "КТО?"?', "Учитель", "Книга", "Парта", "A"),
            ('Допишите вежливое слово: "Спасибо, ......"', "Пожалуйста", "Здравствуйте", "До свидания", "A"),
            ("В каком слове первый звук — гласный?", "Арбуз", "Кот", "Дом", "A"),
            ('Закончите правило: "Сколько в слове гласных, столько и ......"', "букв", "слогов", "звуков", "B"),
        ],
    },
    {
        "grade": 2,
        "subject": "Rus tili",
        "title": "2-sinf Rus tili",
        "questions": [
            ("В каком сочетании букв НЕ пишется мягкий знак (Ь)?", "ЧК / ЧН", "ЛЬ / НЬ", "ТЬ / СЬ", "A"),
            ("Найдите слово, в котором допущена ОШИБКА:", "Ночка", "Дочька", "Речка", "B"),
            ('Как правильно проверить безударную гласную в слове "В...ДА"?', "Водный", "Водичка", "Водяной", "A"),
            ('Укажите слово, в котором на конце нужно писать букву "В", а не "Ф":', "Шар...", "Жира...", "Остро...", "C"),
            ('Какое слово отвечает на вопрос "ЧТО ДЕЛАЕТ?"?', "Ученик", "Бежит", "Красивый", "B"),
            ("На какие вопросы отвечают имена существительные?", "Какой? Какая?", "Что делает?", "Кто? Что?", "C"),
            ('Укажите слово, в котором пропущена буква "О":', "Тр...ва", "Стр...на", "Сл...ны", "C"),
            ("Какое слово является именем прилагательным?", "Веселье", "Весёлый", "Веселиться", "B"),
            ("Найдите слово с разделительным мягким знаком (Ь):", "Пальто", "Соловьи", "Мальчик", "B"),
            ("В каком слове звуков БОЛЬШЕ, чем букв?", "Ягода", "Книга", "Тетрадь", "A"),
            ("В конце какого предложения нужен ВОСКЛИЦАТЕЛЬНЫЙ знак (!)?", "Как тебя зовут", "Какая красивая сегодня погода", "Дети пошли в школу", "B"),
            ("Найдите ОШИБКУ в написании парных согласных:", "Кроватка", "Тетрать", "Ложка", "B"),
            ('Сколько слогов в слове "УЧИТЕЛЬНИЦА"?', "4", "5", "6", "B"),
            ("Какое слово пишется с разделительным ТВЁРДЫМ знаком (Ъ)?", "С...езд", "В...юга", "Пл...тье", "A"),
            ('Какое слово однокоренное к слову "ДОМ"?', "Домашний", "Домино", "Дочка", "A"),
            ('Укажите слово, в котором пропущена буква "И":', "Рощ...", "Лыж...", "Чащ...", "B"),
            ('На какой вопрос отвечает слово "СОЛНЦЕ"?', "Кто?", "Что?", "Какой?", "B"),
            ("Какое слово — ГЛАГОЛ?", "Рисование", "Рисует", "Рисунок", "B"),
            ("Найдите слово, в котором ВСЕ согласные звуки твёрдые:", "Лимон", "Машина", "Чашка", "B"),
            ('Как правильно перенести слово "ЮЛЬКА"?', "Ю-лька", "Юль-ка", "Юльк-а", "B"),
        ],
    },
    {
        "grade": 3,
        "subject": "Rus tili",
        "title": "3-sinf Rus tili",
        "questions": [
            ("Какая часть слова стоит перед корнем и служит для образования новых слов?", "Суффикс", "Приставка", "Окончание", "B"),
            ("Найдите слово, в котором допущена ОШИБКА в написании приставки:", "Сделать", "Зделать", "Побежать", "B"),
            ("Укажите слово, в котором есть непроизносимая согласная Т:", "Честный", "Вкусный", "Ужасный", "A"),
            ("Какое из слов относится к ЖЕНСКОМУ роду?", "Тетрадь", "Дневник", "Облако", "A"),
            ("Найдите слово, которое НЕ имеет формы единственного числа:", "Книги", "Ножницы", "Столы", "B"),
            ('Какое слово является проверочным для гласной в слове "КР...ЧАТЬ"?', "Крик", "Крикун", "Кричащий", "A"),
            ("Укажите слово среднего рода:", "Солнце", "Луна", "Ветер", "A"),
            ("Какая часть слова образует форму слова и служит для связи слов?", "Корень", "Окончание", "Суффикс", "B"),
            ('В каком слове пропущена непроизносимая согласная?', "Мес...ность", "Опас...ный", "Прекрас...ный", "A"),
            ('Определите главные члены в предложении: "Осенние листья тихо падают на землю."', "Осенние листья", "Листья падают", "Падают на землю", "B"),
            ("Укажите слово с разделительным мягким знаком (Ь):", "Речка", "Платье", "Подъезд", "B"),
            ('Какое слово является синонимом к слову "ДРУГ"?', "Враг", "Товарищ", "Сосед", "B"),
            ("Найдите слово с уменьшительно-ласкательным суффиксом:", "Домик", "Дом", "Дома", "A"),
            ("Какое существительное является ОДУШЕВЛЁННЫМ?", "Дерево", "Воробей", "Цветок", "B"),
            ("Укажите слово, в написании которого допущена ОШИБКА:", "Подъезд", "Обьявление", "Съел", "B"),
            ("Какой вопрос нужно задать к прилагательному во множественном числе?", "Какой?", "Какие?", "Какая?", "B"),
            ("В каком слове пишется мягкий знак (Ь) после шипящих на конце?", "Плащ...", "Ноч...", "Мяч...", "B"),
            ('Какое слово является антонимом к слову "ШИРОКИЙ"?', "Большой", "Узкий", "Длинный", "B"),
            ("Укажите слово, которое состоит ТОЛЬКО из корня и окончания:", "Зима", "Поездка", "Зимний", "A"),
            ('В каком слове буква "Е" обозначает два звука [йэ]?', "Река", "Ель", "Лес", "B"),
        ],
    },
    {
        "grade": 4,
        "subject": "Rus tili",
        "title": "4-sinf Rus tili",
        "questions": [
            ('К какому склонению относится существительное "МЫШЬ"?', "1-е склонение", "2-е склонение", "3-е склонение", "C"),
            ("В каком падеже существительное всегда употребляется ТОЛЬКО с предлогом?", "В Дательном", "В Предложном", "В Творительном", "B"),
            ("Найдите глагол, который относится ко II спряжению (исключение):", "Читать", "Смотреть", "Писать", "B"),
            ("Какое окончание имеет прилагательное мужского рода в Родительном падеже?", "-ому / -ему", "-ого / -его", "-ым / -им", "B"),
            ("Укажите слово, в котором после шипящих НЕ пишется мягкий знак (Ь):", "Помощ...", "Ландыш...", "Вещ...", "B"),
            ("Какое личное местоимение относится к 1-му лицу множественного числа?", "Вы", "Они", "Мы", "C"),
            ('В каком слове в корне пишется буква "О"?', "Кв...ртира", "Гр...за", "Тр...винка", "B"),
            ("Укажите глагол в форме прошедшего времени множественного числа:", "Бегали", "Бегут", "Будут бегать", "A"),
            ('В каком слове пропущена непроизносимая согласная "Т"?', "Вкус...ный", "Извес...ный", "Опас...ный", "B"),
            ("Какое существительное относится к 1-му склонению?", "Дядя", "Окно", "Степь", "A"),
            ("Укажите предложение с ОДНОРОДНЫМИ членами:", "Наступила осень, и пошёл дождь.", "В саду росли красные, жёлтые и белые розы.", "Дети прибежали домой.", "B"),
            ('Какое окончание у глагола "ПИСАТЬ" во 2-м лице множественного числа (Вы ...)?', "Пишете", "Пишите", "Пишут", "A"),
            ("В каком слове пишется разделительный твёрдый знак (Ъ)?", "Об...яснение", "В...юга", "Счаст...е", "A"),
            ("Найдите существительное во множественном числе Родительного падежа:", "Деревья", "Друзей", "Столами", "B"),
            ("Какая часть речи указывает на предмет, но не называет его?", "Существительное", "Местоимение", "Прилагательное", "B"),
            ("Укажите глагол-исключение, который относится к I спряжению:", "Слышать", "Брить", "Дышать", "B"),
            ("Какое существительное НЕОДУШЕВЛЁННОЕ и мужского рода?", "Компьютер", "Ручка", "Кукла", "A"),
            ("В каком слове ОШИБКА в написании безударного окончания глагола?", "Он строит", "Он лает", "Он видет", "C"),
            ("На какой вопрос отвечает существительное в Творительном падеже?", "Кого? Чего?", "Кем? Чем?", "Кому? Чему?", "B"),
            ("Укажите слово с удвоенной согласной в корне:", "Класс", "Суббота", "Оба варианта верны", "C"),
        ],
    },
    {
        "grade": 5,
        "subject": "Rus tili",
        "title": "5-sinf Rus tili",
        "questions": [
            ("В каком слове букв БОЛЬШЕ, чем звуков?", "Юность", "Солнце", "Разъезд", "B"),
            ('Укажите слово, в корне которого пишется буква "А":', "Изл...жить", "Предл...гать", "Распол...жение", "B"),
            ('В каком слове в корне пишется "О" (исключение -раст-/-рос-)?', "Р...стение", "Выр...щенный", "Р...сток", "C"),
            ('Найдите строку, где во всех словах после Ц пишется "И":', "Цирк, цифра, нация", "Спицы, цыган, цыпочки", "Курицын, цыплёнок, революция", "A"),
            ('Какое слово является ОМОНИМОМ к слову "КЛЮЧ"?', "Родник", "Замок", "Дверь", "A"),
            ('Укажите слово, в котором после шипящих под ударением пишется "О":', "Ш...пот", "Ш...лк", "Ш...в", "C"),
            ("Какое существительное является НЕСКЛОНЯЕМЫМ?", "Метро", "Окно", "Море", "A"),
            ('В каком слове приставка оканчивается на букву "З"?', "Бе...полезный", "Ра...веселить", "И...портить", "B"),
            ("Найдите предложение с ПРЯМОЙ РЕЧЬЮ:", "Мама сказала, чтобы я сделал уроки.", 'Учитель спросил: "Кто готов?"', "По словам врача, погода будет хорошей.", "B"),
            ('Укажите слово, в котором после приставки пишется "И":', "Без...мянный", "Под...грать", "Сверх...нтересный", "C"),
            ('Какое слово является антонимом к слову "ЕСТЕСТВЕННЫЙ"?', "Натуральный", "Искусственный", "Простой", "B"),
            ("В каком предложении между подлежащим и сказуемым ставится тире?", "Москва — столица России.", "Наступила золотая осень.", "Мы любим читать книги.", "A"),
            ("В каком слове на конце пишется Ь (3-е склонение)?", "Камыш...", "Рож...", "Шалаш...", "B"),
            ("Найдите глагол в форме БУДУЩЕГО СЛОЖНОГО времени:", "Прочитаю", "Буду читать", "Читаю", "B"),
            ("Какое слово является УСТАРЕВШИМ (архаизм)?", "Компьютер", "Очи", "Самолёт", "B"),
            ('Укажите верный разбор по составу слова "ПОДВОДНЫЙ":', "под- / -вод- / -н- / -ый", "подвод- / -н- / -ый", "под- / -водн- / -ый", "A"),
            ("В каком слове пишется разделительный Ъ знак?", "С...экономить", "Под...езд", "Счаст...е", "B"),
            ("Какой второстепенный член отвечает на вопросы косвенных падежей?", "Определение", "Обстоятельство", "Дополнение", "C"),
            ('Укажите слово, где "Ё" после шипящего в корне проверяется словом с "Е":', "Ч...рный", "Крыж...вник", "Капюш...н", "A"),
            ("В каком слове звуков БОЛЬШЕ, чем букв?", "Маяк", "Семья", "Тетрадь", "A"),
        ],
    },
    {
        "grade": 6,
        "subject": "Rus tili",
        "title": "6-sinf Rus tili",
        "questions": [
            ('Укажите разряд местоимения: "Я себя чувствую великолепно."', "Личное", "Возвратное", "Притяжательное", "B"),
            ("В каком числительном мягкий знак (Ь) пишется в середине?", "Пятьдесят", "Пятнадцать", "Одиннадцать", "A"),
            ("Найдите глагол СОВЕРШЕННОГО вида:", "Решать", "Решить", "Переписывать", "B"),
            ('В каком слове в суффиксе после шипящих под ударением пишется "О"?', "Медвеж...нок", "Туш...нка", "Реч...ка", "A"),
            ("Укажите разносклоняемое имя существительное (исключение):", "Время", "Санаторий", "Армия", "A"),
            ("Какое числительное является ПОРЯДКОВЫМ?", "Пятьдесят", "Пятый", "Пятеро", "B"),
            ('В каком варианте "НЕ" пишется СЛИТНО?', "(Не)ряшливый вид", "(Не) широкая, а узкая", "Вовсе (не) интересный", "A"),
            ("Укажите притяжательное имя прилагательное:", "Лисий хвост", "Деревянный стол", "Зимний вечер", "A"),
            ('В каком слове на конце пишется "И" (Родительный падеж на -ия)?', "О лекци...", "Нет истори...", "К Мари...", "B"),
            ("Какое слово является СОБИРАТЕЛЬНЫМ числительным?", "Три", "Третий", "Трое", "C"),
            ("Укажите глагол в форме ПОВЕЛИТЕЛЬНОГО наклонения:", "Сделай", "Сделал бы", "Сделаю", "A"),
            ('В каком слове в приставке пишется "И" (приближение)?', "Пр...ехать", "Пр...красный", "Пр...мудрый", "A"),
            ("Укажите существительное ОБЩЕГО рода:", "Плакса", "Врач", "Профессор", "A"),
            ('В каком слове пишется ОДНА буква "Н" (исключение)?', "Оловянный", "Ветреный", "Стеклянный", "B"),
            ("Найдите отрицательное местоимение:", "Никто", "Кое-кто", "Кто-то", "A"),
            ("Какой глагол является ПЕРЕХОДНЫМ?", "Читать (книгу)", "Идти (в школу)", "Гордиться (победой)", "A"),
            ('В каком слове в суффиксе прилагательного пишется "О"?', "Еж...вый", "Плющ...вый", "Ключ...вой", "A"),
            ("Какое местоимение относится к УКАЗАТЕЛЬНЫМ?", "Этот", "Мой", "Сам", "A"),
            ("Укажите глагол в форме УСЛОВНОГО наклонения:", "Прочитал бы", "Прочитай", "Читает", "A"),
            ('В каком слове пишется суффикс "-К-", а не "-СК-"?', "Француз...ский", "Немец...кий", "Матрос...ский", "B"),
        ],
    },
    {
        "grade": 7,
        "subject": "Rus tili",
        "title": "7-sinf Rus tili",
        "questions": [
            ("Найдите слово, которое является ПРИЧАСТИЕМ:", "Жёлтый", "Желтеющий", "Желтеть", "B"),
            ("В каком причастии суффикс написан БЕЗОШИБОЧНО?", "Таящий (снег)", "Клеющий (карандаш)", "Строящий (дом)", "C"),
            ("Укажите деепричастие СОВЕРШЕННОГО вида:", "Читая", "Прочитав", "Улыбаясь", "B"),
            ("В каком предложении ошибка в деепричастном обороте?", "Подъезжая к станции, у меня слетела шляпа.", "Подъезжая к станции, я потерял шляпу.", "Прочитав книгу, я вернул её.", "A"),
            ('В каком наречии на конце пишется буква "О"?', "Справ...", "Вправ...", "Досух...", "B"),
            ("Укажите страдательное причастие прошедшего времени:", "Прочитанный", "Читаемый", "Читавший", "A"),
            ('В каком варианте "НЕ" с причастием пишется РАЗДЕЛЬНО?', "(Не)годующий взгляд", "(Не)выполненное вовремя задание", "(Не)распечатанное письмо", "B"),
            ('В каком слове в суффиксе причастия пишется "А/Я" (2-е спряжение)?', "Слышащий", "Стелющий", "Тающий", "A"),
            ("Какое слово является НАРЕЧИЕМ?", "Быстрый", "Быстро", "Быстрота", "B"),
            ('В каком кратком причастии пишется ОДНА буква "Н"?', "Книга прочита...а", "Решён...ая задача", "Нарисова...ая картина", "A"),
            ("Укажите наречие, на конце которого НЕ пишется Ь (исключение):", "Настежь", "Уж", "Вскачь", "B"),
            ('В каком слове после приставки пишется буква "Ы"?', "Сверх...нтересный", "Без...нициативный", "Меж...нститутский", "B"),
            ("Какое слово пишется через ДЕФИС?", "(По)немецки", "(По)дороге", "(До)темна", "A"),
            ("Найдите деепричастие НЕСОВЕРШЕННОГО вида:", "Сделав", "Глядя", "Прыгнув", "B"),
            ('В каком причастии под ударением после шипящих пишется "Ё"?', "Освещ...нный", "Больш...й", "Горяч...", "A"),
            ('Укажите строку, во всех словах которой пишется "НН":', "Жареная рыба, решённый пример", "Сломанный стул, купленный товар", "Кожаный диван, сорванный цветок", "B"),
            ("Какое наречие является наречием ВРЕМЕНИ?", "Вчера", "Нарочно", "Громко", "A"),
            ("Какова синтаксическая роль деепричастия в предложении?", "Подлежащее", "Обстоятельство", "Дополнение", "B"),
            ('В каком наречии на конце пишется буква "А"?', "Засветл...", "Искос...", "Наглух...", "B"),
            ("Укажите действительное причастие настоящего времени:", "Рисующий", "Рисовавший", "Нарисованный", "A"),
        ],
    },
    {
        "grade": 8,
        "subject": "Rus tili",
        "title": "8-sinf Rus tili",
        "questions": [
            ('Тип односоставного предложения: "Каждую субботу хожу в библиотеку."', "Безличное", "Определённо-личное", "Неопределённо-личное", "B"),
            ("В каком предложении тире между подлежащим и сказуемым НЕ нужно?", "Жить — родине служить.", "Мой брат — инженер.", "Он очень талантливый художник.", "C"),
            ('Тип односоставного предложения: "В дверь постучали."', "Неопределённо-личное", "Безличное", "Обобщённо-личное", "A"),
            ("В каком предложении выделенное слово является ВВОДНЫМ?", "Этот вопрос кажется очень сложным.", "Поезд, кажется, уже прибыл.", "Всё вокруг кажется зелёным.", "B"),
            ("Какое предложение является БЕЗЛИЧНЫМ?", "Мне не спится.", "Люблю грозу в начале мая.", "Нам принесли свежие газеты.", "A"),
            ("В каком предложении верно употреблено приложение?", "Озеро Байкал — самое глубокое в мире.", "Профессор Иванов прочитал лекцию.", "Врач-терапевт принял пациента.", "A"),
            ("В каком предложении причастный оборот НЕ выделяется запятыми?", "Листья, сорванные ветром, кружились.", "Сорванные ветром листья кружились.", "Листья кружились, сорванные ветром.", "B"),
            ('Каким членом является слово "учиться": "Мы приехали в город учиться"?', "Сказуемое", "Дополнение", "Обстоятельство цели", "C"),
            ("В каком предложении тире при обобщающем слове поставлено верно?", "В саду росли цветы: розы, тюльпаны, лилии.", "Розы, тюльпаны, лилии — все эти цветы росли в саду.", "Все цветы: розы, тюльпаны, лилии, росли в саду.", "B"),
            ('Тип односоставного предложения: "Цыплят по осени считают."', "Неопределённо-личное", "Обобщённо-личное", "Безличное", "B"),
            ("В каком предложении есть обособленное обстоятельство (деепричастный оборот)?", "Он работал спустя рукава.", "Мальчик бежал сломя голову.", "Закончив работу, мы отправились домой.", "C"),
            ("В каком предложении выделенное слово является ОБРАЩЕНИЕМ?", "Дмитрий успешно сдал экзамены.", "Помоги мне, Дмитрий, разобраться.", "Я вспоминаю своего друга Дмитрия.", "B"),
            ('Какой тип сказуемого: "Он был готов помочь нам"?', "Простое глагольное", "Составное глагольное", "Составное именное", "C"),
            ('В каком предложении союз КАК имеет значение "в качестве" (без запятой)?', "Он известен как опытный хирург.", "Воздух чистый, как стекло.", "Пруд, как блестящее зеркало.", "A"),
            ('В каком предложении пишется "И" в отрицательном местоимении?', "Никто не пришёл на встречу.", "Не кто иной, как мой друг.", "Некого было винить.", "A"),
            ('Вид односоставного предложения: "Тишина. Ночь. Звёздное небо."', "Назывное", "Безличное", "Определённо-личное", "A"),
            ("В каком варианте деепричастный оборот употреблён ВЕРНО?", "Читая книгу, у меня заболели глаза.", "Читая книгу, я узнал много нового.", "Читая книгу, мне стало скучно.", "B"),
            ("Какое слово является составным подчинительным союзом?", "Потому что", "Чтобы", "Однако", "A"),
            ("В каком предложении запятая перед И НЕ ставится?", "Солнце взошло, и туман рассеялся.", "Ветер дул с севера и уносил листья.", "Наступила ночь, и зажглись звёзды.", "B"),
            ('Какой знак пропущен: "Я знаю главное (_) честность важнее всего"?', "Запятая", "Двоеточие", "Тире", "B"),
        ],
    },
    {
        "grade": 9,
        "subject": "Rus tili",
        "title": "9-sinf Rus tili",
        "questions": [
            ('Тип сложного предложения: "Солнце взошло, и всё преобразилось."', "ССП (сложносочинённое)", "СПП (сложноподчинённое)", "БСП (бессоюзное)", "A"),
            ('Тип придаточного: "Мы вернулись в город, где провели детство."', "Изъяснительное", "Определительное", "Места", "B"),
            ("В каком БСП нужно поставить ДВОЕТОЧИЕ?", "Погода была ужасной, на улицу никто не выходил.", "Я знаю, ты сдашь этот экзамен.", "Сыр выпал, с ним была плутовка такова.", "B"),
            ('Тип придаточного: "Я не знаю, когда начнётся конференция."', "Времени", "Изъяснительное", "Определительное", "B"),
            ("В каком предложении перед И запятая НЕ ставится (общий член)?", "Взошло солнце, и птицы запели.", "Взошло солнце, и туман рассеялся.", "В середине мая зацвели сады и воздух наполнился ароматом.", "C"),
            ("Укажите предложение с придаточным УСТУПИТЕЛЬНЫМ:", "Мы пошли гулять, несмотря на то что лил дождь.", "Если будет погода, мы пойдём в горы.", "Так как автобус опоздал, я пропустил лекцию.", "A"),
            ('Значение тире в БСП: "Выглянет солнце — всё оживёт"?', "Противопоставление", "Быстрая смена событий / условие", "Причина", "B"),
            ('Тип подчинения: "Я уверен, что если мы постараемся, то проект будет сдан."', "Последовательное", "Однородное", "Параллельное", "A"),
            ("В каком предложении ОШИБКА в пунктуации при стыке союзов?", "Он сказал, что, если погода испортится, экскурсию отменят.", "Он сказал, что если погода испортится, то экскурсию отменят.", "Он сказал, что, если погода испортится, то экскурсию отменят.", "C"),
            ('Тип сложного предложения: "Пашню пашут — руками не машут."', "ССП", "БСП", "СПП", "B"),
            ("В каком предложении придаточное можно заменить причастным оборотом?", "Книга, которую подарил друг, оказалась интересной.", "Я прочитал книгу, когда появилось время.", "Он думал о книге, которую предстоит написать.", "A"),
            ("В каком БСП между частями ставится ЗАПЯТАЯ?", "Сыр выпал, лисица его подхватила.", "Метель не утихала, небо оставалось мутным.", "Я поднял глаза: зажглись первые звёзды.", "B"),
            ('Вид придаточного: "Он так изменился, что я едва узнал его."', "Образа действия и степени", "Следствия", "Определительное", "A"),
            ("В каком варианте выделенное слово — СОЮЗНОЕ СЛОВО?", "Я знаю, что ты любишь читать.", "Книга, что лежала на столе, профессора.", "Он сказал, что приедет вовремя.", "B"),
            ('Значение двоеточия: "Я не пришёл: у меня заболел брат"?', "Пояснение", "Дополнение", "Причина", "C"),
            ("Укажите предложение с придаточным ЦЕЛИ:", "Мы учимся для того, чтобы приносить пользу.", "Мы так устали, что сразу легли спать.", "Что бы он ни делал, всё получалось.", "A"),
            ("Какое предложение является сложным С РАЗНЫМИ ВИДАМИ СВЯЗИ?", "Когда мы подошли, дверь была заперта, но в окнах горел свет.", "Дверь была заперта, и свет не горел, потому что все спали.", "Оба варианта", "C"),
            ('Тип придаточного: "Мы поехали туда, где строился кампус."', "Определительное", "Места", "Изъяснительное", "B"),
            ("В каком БСП нужно поставить ТИРЕ (противопоставление)?", "Лето припасает — зима поедает.", "Птицы запели, лес ожил.", "Я посмотрел в окно: шёл снег.", "A"),
            ('Схема предложения: "Учитель сказал, что оценки объявят, когда директор подпишет приказ."', "[ ], (что...), (когда...) — последовательное", "[ ], (что...), [когда...]", "(Когда...), [ ], (что...)", "A"),
        ],
    },
    {
        "grade": 10,
        "subject": "Rus tili",
        "title": "10-sinf Rus tili",
        "questions": [
            ("Определите стиль речи: текст официального договора.", "Публицистический", "Официально-деловой", "Научный", "B"),
            ('Какое слово является ПАРОНИМОМ к слову "ОДЕТЬ"?', "Надеть", "Раздеть", "Обуть", "A"),
            ('В каком предложении фразеологизм означает "очень быстро"?', "Он работал не покладая рук.", "Мы бежали со всех ног.", "Сосед любит заговаривать зубы.", "B"),
            ("В каком слове ОШИБКА в ударении?", "Позво́нишь", "Обеспе́чение", "Догово́р", "A"),
            ('Какое слово является КНИЖНЫМ синонимом к "УМЕНЬШИТЬ"?', "Снизить", "Нивелировать", "Урезать", "B"),
            ("В каком предложении союз КАК выделяется запятыми (сравнение)?", "Он вёл себя как настоящий герой.", "Её глаза, как звёзды, сияли в темноте.", "Книга известна как лучшее пособие.", "B"),
            ("Какое слово является ЗАИМСТВОВАННЫМ?", "Корифей", "Пролонгировать", "Оба варианта заимствованные", "C"),
            ("В каком предложении ЛЕКСИЧЕСКАЯ ОШИБКА (плеоназм)?", "Мы поднялись вверх по лестнице.", "В октябре месяце идут дожди.", "Оба варианта содержат ошибку", "C"),
            ('Что означает фразеологизм "Яблоко раздора"?', "Причина спора, вражды", "Очень ценный подарок", "Быстрая победа", "A"),
            ("В каком предложении ошибка в управлении (падеж)?", "Благодаря хорошей погоде мы поехали на дачу.", "Согласно приказа директора, день сокращён.", "Вопреки ожиданиям, экзамен был лёгким.", "B"),
            ('Какое слово является АНТОНИМОМ к "АЛЬТРУИСТ"?', "Гуманист", "Эгоист", "Филантроп", "B"),
            ("Укажите предложение с обособленным ПРИЛОЖЕНИЕМ:", "Мы, студенты университета, посетили выставку.", "Уставшие после дороги, мы легли спать.", "Несмотря на поздний час, горел свет.", "A"),
            ('В каком слове в суффиксе пишется "Ё" (отглагольное)?', "Стаж...ровка", "Нож...вка", "Туш...нка", "C"),
            ('К какому типу лексики относится слово "ОЧИ"?', "Историзм", "Архаизм", "Диалектизм", "B"),
            ('Синтаксический синоним к "Когда мы закончили проект, мы представили его директору":', "Закончив проект, мы представили его директору.", "Проект был закончен и представлен.", "Мы закончили проект, чтобы представить его.", "A"),
            ("Какой стиль используется на митингах и в газетах?", "Разговорный", "Публицистический", "Официально-деловой", "B"),
            ('Что означает слово "ЭФЕМЕРНЫЙ"?', "Вечный, прочный", "Призрачный, мимолётный", "Полезный, эффективный", "B"),
            ("В каком предложении тире ставится на месте пропущенного члена?", "Книга — источник знаний.", "Мы поехали в Самарканд, а они — в Бухару.", "Жизнь прожить — не поле перейти.", "B"),
            ("Какое слово пишется СЛИТНО?", "(В) течение часа", "(В)виду болезни", "(В) продолжение темы", "B"),
            ('В каком предложении пишется ОДНА буква "Н"?', "Девочка была воспитанна и вежлива.", "Она была воспитана в строгих традициях.", "Дети были невнимательны.", "B"),
        ],
    },
    {
        "grade": 11,
        "subject": "Rus tili",
        "title": "11-sinf Rus tili",
        "questions": [
            ("Где пишется НН: крашеный краской стол(1), расставлены(2) кресла, плетёные(3), купленные(4)?", "1, 4", "1, 2, 4", "2, 4", "A"),
            ("Укажите предложение, где НЕ со словом пишется РАЗДЕЛЬНО:", "Этот человек нам далеко не знаком.", "Впереди ждал не исследованный учёными перевал.", "Оба варианта раздельно", "C"),
            ('В каком слове на месте пропуска пишется буква "Е"?', "Продл...вать", "Затм...вать", 'Оба варианта с "Е"', "C"),
            ('Какое слово — пароним к "ДИПЛОМАТ" (человек, получивший диплом)?', "Дипломант", "Дипломатник", "Дипломатия", "A"),
            ("Какое предложение ГРАММАТИЧЕСКИ ВЕРНО (деепричастный оборот)?", "Возвращаясь домой, меня застал ливень.", "Прочитав рукопись, редактору показалось...", "Проанализировав результаты, учёные пришли к выводам.", "C"),
            ("В каком предложении нужна ТОЛЬКО ОДНА запятая?", "Не было видно ни лиц ни фигур ни очертаний дома.", "Ветер срывал листья с деревьев и гнал их по саду.", "Наступила осень и птицы начали улетать.", "C"),
            ('В каком слове после шипящего в суффиксе пишется "О"?', "Отреш...нный", "Нож...вка", "Печ...шь", "B"),
            ("В каком предложении выделенное слово является ВВОДНЫМ?", "Решение задачи очевидно для каждого.", "Поезд, напротив, пришёл вовремя.", "Ваше поведение кажется странным.", "B"),
            ("Какое слово пишется ЧЕРЕЗ ДЕФИС?", "(По)одиночке", "(По)английски", "(По)тихоньку", "B"),
            ('Что означает фразеологизм "Перейти Рубикон"?', "Сделать решительный, бесповоротный шаг.", "Потерпеть полное поражение.", "Найти компромисс в споре.", "A"),
            ("В каком БСП ставится ТИРЕ (—)?", "Я посмотрел назад: на дороге никого не было.", "Наступит утро — птицы запоют.", "Погода была отличной: солнце светило ярко.", "B"),
            ('В каком слове после приставки пишется буква "И"?', "Пост...нфарктный", "Без...дейный", "Сыграть", "A"),
            ('Какой стиль речи строго логичен, с вводными "следовательно", "таким образом"?', "Публицистический", "Научный", "Официально-деловой", "B"),
            ("Какое существительное в Род. падеже мн. числа имеет нулевое окончание?", "Килограммов", "Партизан", "Помидоров", "B"),
            ('В каком слове пишется "Ь" (мягкий знак)?', "Спряч...ся", "Горяч...", "Много задач...", "A"),
            ('Какое слово является антонимом к "ЛАКОНИЧНЫЙ"?', "Краткий", "Многословный", "Скупой", "B"),
            ('В каком варианте "НЕ"/"НИ" выбрано ВЕРНО?', "Кто ни читал эту книгу, все были в восторге.", "Я не мог не согласиться с доводами.", "Оба варианта верны", "C"),
            ('Какое слово означает "умышленное сокрытие истины"?', "Филантропия", "Мистификация", "Диссимуляция", "C"),
            ("Укажите предложение с ОШИБКОЙ в согласовании причастного оборота:", "Мы гордимся студентами, сдавшими экзамен.", "Я восхищался городом, поразившим меня красотой.", "Мы встретили туристов, приехавших и которые направлялись в Ташкент.", "C"),
            ("Какой знак пропущен: Любовь, верность, честность (_) все эти качества ценятся?", "Двоеточие", "Тире", "Запятая", "B"),
        ],
    },
]


class Command(BaseCommand):
    help = "Seed English olympiad tests (grades 2-6) into the database."

    def handle(self, *args, **options):
        for test_def in TESTS:
            subject_name = test_def.get("subject", SUBJECT_NAME)
            subject, _ = Subject.objects.get_or_create(
                name=subject_name, defaults={"is_active": True}
            )

            test, created = Test.objects.get_or_create(
                grade=test_def["grade"],
                subject=subject,
                title=test_def["title"],
                defaults={
                    "duration_minutes": DURATION_MINUTES,
                    "passing_percentage": PASSING_PERCENTAGE,
                    "is_active": True,
                },
            )

            if test.questions.exists():
                self.stdout.write(
                    f"SKIP: '{test.title}' allaqachon savollarga ega ({test.questions.count()} ta)."
                )
                continue

            for i, (text, a, b, c, correct) in enumerate(test_def["questions"], start=1):
                Question.objects.create(
                    test=test,
                    order_number=i,
                    question_text=text,
                    option_a=a,
                    option_b=b,
                    option_c=c,
                    option_d="",
                    correct_answer=correct,
                )

            self.stdout.write(
                self.style.SUCCESS(
                    f"OK: '{test.title}' yaratildi, {len(test_def['questions'])} ta savol qo'shildi."
                )
            )

        self.stdout.write(self.style.SUCCESS("Tugadi."))
