# Generated by Django 6.0.5 on 2026-05-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='Test tugash vaqti', null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='start_datetime',
            field=models.DateTimeField(blank=True, help_text='Test boshlanish vaqti', null=True),
        ),
    ]
