# Generated by Django 6.0.5 on 2026-05-18 07:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_id', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('grade', models.IntegerField(help_text='1-11 sinf')),
                ('subject', models.CharField(max_length=100)),
                ('payment_type', models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('cash', 'Naqd')], max_length=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', "To'langan"), ('rejected', 'Rad etilgan')], default='pending', max_length=20)),
                ('verification_status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20)),
                ('unique_code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('passport_or_birth_cert', models.URLField(blank=True, help_text='Supabase Image URL', null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('cash', 'Naqd')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=190000.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='registration.participant')),
            ],
        ),
    ]
