# Generated by Django 6.0.5 on 2026-05-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='telegram_id',
            field=models.CharField(max_length=50),
        ),
    ]
