# Generated by Django 6.0.5 on 2026-05-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_participant_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='call_status',
            field=models.CharField(choices=[('new', 'Yangi'), ('no_answer', "Ko'tarmadi"), ('confirmed', 'Keladi'), ('declined', 'Rad etildi')], default='new', max_length=20),
        ),
    ]
